### ISSUE TITLE
Restart fails

### ISSUE THREAD

**Issue by grrosminet** [IngoZenz/personaldnsfilter#100] opened 2020-08-08 05:30 UTC
Hi ! 

Refularily when i change network, i got errors. 
Here is today wake up, changing from airplane to wifi

It's on a galaxy s10

`****This is personalDNSfilter V+1504100****

Initializing ...
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=dnsfilter.android/.DNSFilterService }: app is in background uid UidRecord{e1c539b u0a302 TPSL idle procs:1 proclist:28542, seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1688)
	at android.app.ContextImpl.startService(ContextImpl.java:1633)
	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
	at dnsfilter.android.DNSProxyActivity.startSvc(DNSProxyActivity.java:1439)
	at dnsfilter.android.DNSProxyActivity.startup(DNSProxyActivity.java:1427)
	at dnsfilter.android.DNSProxyActivity.loadAndApplyConfig(DNSProxyActivity.java:837)
	at dnsfilter.android.DNSProxyActivity.initAppAndStartup(DNSProxyActivity.java:755)
	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:542)
	at android.app.Activity.performCreate(Activity.java:7957)
	at android.app.Activity.performCreate(Activity.java:7946)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
`

**Comment by IngoZenz** [comment] 2020-08-08 06:05
Could you describe the detailed steps to get this error?
From the log it looks like you activly started the app?
Can you always reproduce this error?

**Comment by grrosminet** [comment] 2020-08-08 09:32
Hi,
as I said, Regularily when i change network, i got problems : network is no more available. It's not systematic and when it happens, I have to disconnect the virtual vpn
today I got the above error and I thought it could be related to my problem

**Comment by IngoZenz** [comment] 2020-08-08 09:57
did this error above  occur immediately when changing from airplane to WiFi? That's unlikely as the error above is during starting the app...
In case there are different issues, please do not mix them up as it will make it very difficult for me to understand the problem

**Comment by IngoZenz** [comment] 2020-09-05 08:05
As there was no update since long time I am closing this...

**Closed by IngoZenz** 2020-09-05 08:05 UTC
