### ISSUE TITLE
[Bug] App doesn't seem to be aware of changes in Wi-Fi state

### ISSUE THREAD

**Issue by opusforlife2** [IngoZenz/personaldnsfilter#54] opened 2019-12-04 05:44 UTC
Several times, after turning off Wi-Fi and then later turning it on, a DNS timeout error is shown in the log, and the app switches to the next DNS provider in the list.

Ideally, the app should be aware that Wifi was turned off and send the request again when it is turned on.

**Comment by ckuethe** [comment] 2019-12-04 17:38
Duplicate of #53?

**Comment by opusforlife2** [comment] 2019-12-04 22:29
@ckuethe No. That issue is regarding automatic discovery of a DNS provider. I have that disabled.

**Comment by IngoZenz** [comment] 2019-12-05 12:39
will improve this with next version ... DNS switch only in case network is connected

**Comment by IngoZenz** [comment] 2019-12-06 08:45
https://github.com/IngoZenz/personaldnsfilter/commit/558e4d3f02746d9c36f9d33c2bf5dc8b684944a3

**Comment by IngoZenz** [comment] 2019-12-29 17:39
Fix is released with https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.35.0

**Closed by IngoZenz** 2019-12-29 17:39 UTC
