### ISSUE TITLE
YouTube Showing Ads

### ISSUE THREAD

**Issue by GKid94** [IngoZenz/personaldnsfilter#72] opened 2020-03-13 14:21 UTC
![Screenshot_2020-03-13-15-17-17](https://user-images.githubusercontent.com/18757054/76629060-06855300-653e-11ea-9b48-b3502e5cfd69.png)
![Screenshot_2020-03-13-15-20-26](https://user-images.githubusercontent.com/18757054/76629203-37658800-653e-11ea-92bb-7fb11f4ff9f0.png)
![Screenshot_2020-03-13-15-20-33](https://user-images.githubusercontent.com/18757054/76629213-3c2a3c00-653e-11ea-97ee-a070b970cb72.png)

**Comment by IngoZenz** [comment] 2020-03-14 08:26
This is not a bug in pDNSf. It is releated to the way youtube provides ads.
There are many discussion threads on the youtube ads topic arround. You might check and discuss there. As there is nothing pDNSf can do, I close this issue.

**Closed by IngoZenz** 2020-03-14 08:26 UTC
