### ISSUE TITLE
[Bug] Past two updates silently activate "Enable blocking"

### ISSUE THREAD

**Issue by opusforlife2** [IngoZenz/personaldnsfilter#55] opened 2019-12-06 18:04 UTC
Just as the title says. I have blocking disabled. When I opened the app after these last two updates, I found it enabled, and the logger went crazy and started flooding with errors because I have no filter lists. Then I had to disable it and restart the app.

**Comment by IngoZenz** [comment] 2019-12-07 13:08
I was not able to reproduce this with the given information.

**Comment by opusforlife2** [comment] 2019-12-07 17:36
Oh. My bad. I can see the ambiguity.

When I updated from 1.50.33.5 to 1.50.34.3  and later from 1.50.34.3 to 1.50.34.4, I found "Enable blocking" activated when I opened the app. It needs to stay off if it was off on the previous version of the app.

**Comment by IngoZenz** [comment] 2019-12-07 17:54
Now I see the issue...
Will fix this for the next release! Thanks for letting me know

**Comment by IngoZenz** [comment] 2019-12-29 17:38
Fix is released with https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.35.0

**Closed by IngoZenz** 2019-12-29 17:38 UTC
