### ISSUE TITLE
DNS filter not stoping on china mobiles like huawei

### ISSUE THREAD

**Issue by AhmadKamboh786** [IngoZenz/personaldnsfilter#81] opened 2020-04-07 18:32 UTC
When I stop the vpn by click on close button. Vpn not stopping. When I debug the code, stop vpn code run sccessfully but it can't stop the vpn. After 10 to 20 second this line execute again. Basically thread is busy in in.read(data) therefor in that thread dose not interrupt. kindly provide me better solution.Thanks  

//FileInputStream
length = in.read(data);

**Comment by IngoZenz** [comment] 2020-04-08 06:25
Never saw that anywhere - when exiting, the app it does an System.exit(0) which usually stops the whole process.
Please provide your system details.

**Comment by AhmadKamboh786** [comment] 2020-04-08 06:40
No i cant configured always-on vpn. Basically when i stop  the vpn, key sign on mobile top bar can't go. It is due to  thread that is stuck on length = in.read(data);.  you can see this issue also on emulator.

**Comment by IngoZenz** [comment] 2020-04-08 07:43
there shouldn't be an issue with that as a System.exit() is also executed. So the VPN terminates. I cannot reproduce your issue here.

**Comment by IngoZenz** [comment] 2020-05-09 13:52
Any more details on that issue?

**Comment by IngoZenz** [comment] 2020-05-23 13:41
No more response - so closing ...

**Closed by IngoZenz** 2020-05-23 13:41 UTC
