### ISSUE TITLE
https://hosts-file.net/ad_servers.txt no longer available

### ISSUE THREAD

**Issue by KlugB** [IngoZenz/personaldnsfilter#96] opened 2020-07-21 17:41 UTC
Is there a replacement? The app does not seem to block anything anymore... (LG G8s, Android 9, V 1504100, "Block rate 0%")

Even stranger: Version 1503600 on another phone (LG G4, Android 6) still blocks ads. (for example on android-hilfe.de)

**Comment by IngoZenz** [comment] 2020-07-21 18:32
Please restore default configuration via "backup and restore" in advanced settings.

**Comment by KlugB** [comment] 2020-07-21 18:39
Thanks, I can see the "pgl.yoyo.org" entry now.

But I'm still getting ads in Chrome. Is this a different issue?

**Comment by IngoZenz** [comment] 2020-07-21 19:08
With its default settings, chrome misbehaves by bypassing the system dns.

I copied this info from our telegram channel:

badmojr:
If you're using Chrome, you need to disable data saver and Async DNS. Google uses by default two technologies that interfere with host blocking.

1. To disable data saver, tap the three vertical dots in chrome, go to settings, search for "data saver" and disable it.

2. To disable async dns, go to chrome://flags in your browser, search for dns and disable the asynchronous dns feature.

3. In your phone, go to Settings -> Applications -> Chrome -> Storage and clear cache.

4. Reboot!

**Comment by KlugB** [comment] 2020-07-21 20:13
1. is called "Lite-Modus" on my device. This workaround seems like a major drawback to me, unless the saving of traffic by removing ads is bigger than the saving by lite mode. Do you have any estimates about this?
2. I can find no such setting in chrome://flags

**Comment by IngoZenz** [comment] 2020-07-21 20:57
1. No estimate on my side
2. It is named "Async DNS resolver"

**Comment by KlugB** [comment] 2020-07-21 21:51
This option is not available on Chrome 84.0.4147.89 for Android

**Comment by IngoZenz** [comment] 2020-07-23 18:27
OK seems chrome changed ... Google usually wants to see what you are doing ...
Is it working when diabling lite mode?

**Comment by KlugB** [comment] 2020-07-24 10:25
Unfortunately, disabling lite mode is not working. I think I'll switch to Opera or Brave for all tasks that do not need my Google account.

**Comment by IngoZenz** [comment] 2020-07-24 10:46
Unfortunately I cannot reproduce the issue on my phone - no clue why ...

It would help me, if you could try, if enabling the following setting within dnsfilter.conf helps:


# routeIPs - Only for Android VPN based version (requires at least Android 5.1).
# List of IPs routed in addition to the (virtual) DNS (configured by the VPN) to the DNSFilter.
# This might be usefull in case applications ignore the VPN's DNS and just use an own DNS Server,
# such as the Googles DNS Servers
# default = "". Uncomment setting below for using this option.
# As an example below the list of Google DNS servers for IPV4 and IPV6.
routeIPs = 8.8.8.8; 8.8.4.4; 2001:4860:4860::8888; 2001:4860:4860::8844

**Comment by KlugB** [comment] 2020-07-24 11:04
I enabled the setting, but I can see no difference in Chrome - ads are still being displayed.

**Comment by IngoZenz** [comment] 2020-08-04 12:54
what are your secure dns settings within network settings?  Maybe switching it "off" helps.
I tried also to reproduce on emulator but with no success  :-(

**Comment by KlugB** [comment] 2020-08-04 13:48
If you mean the "Private DNS" setting within Android settings, it was set to "Auto". Setting it to "Off", however, did not have any effect on the problem.

**Comment by portiktamas** [comment] 2020-08-14 19:37
Switch to Brave or Firefox and the ads will disappear. If not, you can always install uBlock origin for Firefox and it will work like on desktop. But for every other app the personaldnsfilter must do it's job. :)

**Comment by IngoZenz** [comment] 2020-09-05 08:19
I would be interrested if adding your ISPs DNS IPs here would help:
```
# As an example below the list of Google DNS servers for IPV4 and IPV6.
routeIPs = 8.8.8.8; 8.8.4.4; 2001:4860:4860::8888; 2001:4860:4860::8844
```

**Comment by KlugB** [comment] 2020-09-06 10:40
Via http://www.whatsmydnsserver.com/ I found the Vodafone DNS IPs and edited dnsfilter.conf to:

`routeIPs = 176.95.16.37; 176.95.16.38`

No change in behaviour, as far as I can see. Neither when I'm connected via mobile network, nor via WLAN.

**Comment by IngoZenz** [comment] 2020-09-06 10:51
Thanks for testing.

Just to make sure the correct DNS IPs are taken: 

- Connect Wlan,

- Run dnsleak test via https://www.dnsleaktest.com/results.html

- add detected IPs to routeIPs while dns filter is stopped

- start dns filter and try again whie conected to your wlan

 

Sorry for bothering you wth this ...

**Comment by IngoZenz** [comment] 2020-09-06 11:32
would also be interesting to know what dnsleak detected...

**Comment by KlugB** [comment] 2020-09-06 12:10
> - Run dnsleak test via https://www.dnsleaktest.com using chrome 

-> 81.173.194.68 res3.netcologne.de

> - add detected IPs to routeIPs while dns filter is stopped - start dns filter and try again whie conected to your wlan

Still seeing ads in Chrome.

**Comment by IngoZenz** [comment] 2020-09-06 12:18
is it the same result when dnsfilter is running?

-> 81.173.194.68 res3.netcologne.de

 

Please add all net cologne dns servers to routeIP

 

https://www.netcologne.de/privatkunden/hilfe-detail?faq=1288

**Comment by IngoZenz** [comment] 2020-09-06 13:55
you might try with this dev version - please first be in wifi (or mobile)  then start attached pdnsf dev version for testing (the dev version is only for testing my assumption and not handling network change correctly)

[DNSFilter-1504200-dev01.zip](https://github.com/IngoZenz/personaldnsfilter/files/5179734/DNSFilter-1504200-dev01.zip)

**Comment by KlugB** [comment] 2020-09-06 14:02
> is it the same result when dnsfilter is running? -> 81.173.194.68 res3.netcologne.de

Yes.

> Please add all net cologne dns servers to routeIP   https://www.netcologne.de/privatkunden/hilfe-detail?faq=1288

I added the 2 servers. Still seeing ads.

Before I did this, I noticed I could not refresh my emails. One other app did not have internet access either. After I added the 2 DNS servers and restarted dnsfilter, I have normal internet access again as it seems.

**Comment by KlugB** [comment] 2020-09-06 14:06
> you might try with this dev version - please first be in wifi (or mobile) then start attached pdnsf dev version for testing (the dev version is only for testing my assumption and not handling network change correctly yet)

Sorry, I currently do not have the time for that intense error search. Right now I'm happy with Opera.

BTW, dnsfilter doesn't block ads in [LEO](https://play.google.com/store/apps/details?id=org.leo.android.dict) either, if that's of any help.

**Comment by IngoZenz** [comment] 2020-09-06 14:13
Yes Sure - No problem!

Thanks for your time and help so far - it gave already valuable hints.

I will try to fix this issue in the new version - I have already some ideas...

**Comment by KlugB** [comment] 2020-09-11 13:19
I don't know, if this helps, but yesterday my LG G8s Thinq got Android 10 (OTA) and it seems that dnsfilter is working as expected again. I noticed that ads get blocked in Chrome again, and so far I haven't seen only one ad in Duolingo which has been bugging me quite extensively with ads after almost every lesson.

**Comment by IngoZenz** [comment] 2020-09-24 11:11
The issue should be fixed in latest version - you'll need to enable the setting "routerUnderlyingDNS"

**Closed by IngoZenz** 2020-09-24 11:11 UTC
