### ISSUE TITLE
No app icon after installation

### ISSUE THREAD

**Issue by zputnyq** [IngoZenz/personaldnsfilter#126] opened 2020-12-03 08:03 UTC
Hi,
It's my first time using this app
I have a non rooted xiomi device (note2) with miui 9.6.3.0 global stable based on android 5.0.2.
When I installed pdnsf v 1.50.44.0, the app icon doesn't appear. Installation seems no problem

**Comment by ryder203** [comment] 2020-12-03 11:23
You got a Redmi Note 2 or a Mi Note 2? Sorry, but that must be your outdated MIUI version then. Did you try to apply the default theme in the theme app? I've tested what you described on four real and virtual devices with Android 11, 10,  5.1 and Android 4.2.2 but can not reproduce the error. You are the only one of hundreds of users reporting that, so I guess it's your system, not the app's fault.

**Comment by zputnyq** [comment] 2020-12-03 11:39
I have redmi note 2, not my main device, I rarely tingker it. Yes it's no longer getting an update.
Ok thank you, finally get the fix by using its default theme. Before, I use a theme named limitless, I forgot it's provided or I had downloaded it long time ago

**Comment by IngoZenz** [comment] 2021-01-09 10:31
so this issue seems to be solved - closing!

**Closed by IngoZenz** 2021-01-09 10:31 UTC
