### ISSUE TITLE
release 1.50.55.1 keeps stopping on Android 11

### ISSUE THREAD

**Issue by scollovati** [IngoZenz/personaldnsfilter#286] opened 2024-01-31 10:52 UTC
HI,
with the new release 1.50.55.1 the app no more starts (i.e. Android tells that "it keeps stopping") on Android 11.

Version 1.50.54.1 was fine.

The app is installed from F-DROID.

**Comment by versus004** [comment] 2024-01-31 11:31
Same issue here :
- App version : 1.50.55.1 (from F-DROID)
- Android Version : 13 (MIUI 14.0.5)

**Comment by MatthieuQ** [comment] 2024-01-31 11:53
Same issue on android 14, Samsung A52s

**Comment by illdeletethis** [comment] 2024-01-31 12:05
Android 11 as well, same issue

**Comment by IngoZenz** [comment] 2024-01-31 12:46
Could someone edit the dnsfilter.conf and set "debug = true"? Once done start the app 2 times and after this check  for  a Logcat_file.txt file created in the data folder. Please send this file.
Thank you!

**Comment by IngoZenz** [comment] 2024-01-31 14:42
Thanks .. from which version are you coming?

**Comment by IngoZenz** [comment] 2024-01-31 14:52
@ShenstonePorter - what was the previous version which you updated?

**Comment by IngoZenz** [comment] 2024-01-31 15:25
@ShenstonePorter , in case you have some time, could you check if this is reproducible after reverting to 1.50.54.1 and updating again?. Unfortunately  I cannot reproduce the issue here and the issue seems more complicated.
If this is reproducible it would be great if you could send the complete config folder of your 1.50.54.1 config before updating.

**Comment by IngoZenz** [comment] 2024-01-31 16:17
In case someone currently facing the crash, please also send the config folder of the crashing app - this will help to find the issue.
From the data folder of pDNSf send the following files: `additionalhosts.txt, dnsfilter.conf, dnsfilter-1505401.conf and VERSION.TXT`.

**Comment by IngoZenz** [comment] 2024-01-31 18:17
@ShenstonePorter Thanks a lot - would be great if you could also send the files after the update when it is crashing :-)

**Comment by IngoZenz** [comment] 2024-01-31 18:42
Thanks @ShenstonePorter! I can now reproduce the error!

**Comment by illdeletethis** [comment] 2024-02-01 19:12
Lovely to see a fix already!
How long does it usually take to arrive on fdroid?

**Comment by IngoZenz** [comment] 2024-02-02 07:26
@illdeletethis, could be arround 3 days

**Comment by MatthieuQ** [comment] 2024-02-02 14:44
> Same issue on android 14, Samsung A52s

Here is the logcat



--------- beginning of crash
01-31 12:13:18.979 23815 23815 E AndroidRuntime: FATAL EXCEPTION: main
01-31 12:13:18.979 23815 23815 E AndroidRuntime: Process: dnsfilter.android, PID: 23815
01-31 12:13:18.979 23815 23815 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{dnsfilter.android/dnsfilter.android.DNSProxyActivity}: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:603)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8944)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8913)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	... 12 more
01-31 12:13:18.979 23815 23815 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at dnsfilter.android.FilterConfig.setEntries(FilterConfig.java:128)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity$3.run(DNSProxyActivity.java:994)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:7848)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.loadAndApplyConfig(DNSProxyActivity.java:1024)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.initAppAndStartup(DNSProxyActivity.java:904)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:598)
01-31 12:13:18.979 23815 23815 E AndroidRuntime: 	... 16 more
01-31 12:13:20.360 23870 23870 E AndroidRuntime: FATAL EXCEPTION: main
01-31 12:13:20.360 23870 23870 E AndroidRuntime: Process: dnsfilter.android, PID: 23870
01-31 12:13:20.360 23870 23870 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{dnsfilter.android/dnsfilter.android.DNSProxyActivity}: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:603)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8944)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8913)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	... 12 more
01-31 12:13:20.360 23870 23870 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at dnsfilter.android.FilterConfig.setEntries(FilterConfig.java:128)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity$3.run(DNSProxyActivity.java:994)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:7848)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.loadAndApplyConfig(DNSProxyActivity.java:1024)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.initAppAndStartup(DNSProxyActivity.java:904)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:598)
01-31 12:13:20.360 23870 23870 E AndroidRuntime: 	... 16 more
01-31 12:13:29.532 23972 23972 E AndroidRuntime: FATAL EXCEPTION: main
01-31 12:13:29.532 23972 23972 E AndroidRuntime: Process: dnsfilter.android, PID: 23972
01-31 12:13:29.532 23972 23972 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{dnsfilter.android/dnsfilter.android.DNSProxyActivity}: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:603)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8944)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8913)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	... 12 more
01-31 12:13:29.532 23972 23972 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at dnsfilter.android.FilterConfig.setEntries(FilterConfig.java:128)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity$3.run(DNSProxyActivity.java:994)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:7848)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.loadAndApplyConfig(DNSProxyActivity.java:1024)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.initAppAndStartup(DNSProxyActivity.java:904)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:598)
01-31 12:13:29.532 23972 23972 E AndroidRuntime: 	... 16 more
01-31 12:55:10.601 32335 32335 E AndroidRuntime: FATAL EXCEPTION: main
01-31 12:55:10.601 32335 32335 E AndroidRuntime: Process: dnsfilter.android, PID: 32335
01-31 12:55:10.601 32335 32335 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{dnsfilter.android/dnsfilter.android.DNSProxyActivity}: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:603)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8944)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8913)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	... 12 more
01-31 12:55:10.601 32335 32335 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at dnsfilter.android.FilterConfig.setEntries(FilterConfig.java:128)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity$3.run(DNSProxyActivity.java:994)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:7848)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.loadAndApplyConfig(DNSProxyActivity.java:1024)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.initAppAndStartup(DNSProxyActivity.java:904)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:598)
01-31 12:55:10.601 32335 32335 E AndroidRuntime: 	... 16 more
01-31 23:10:45.822 11507 11507 E AndroidRuntime: FATAL EXCEPTION: main
01-31 23:10:45.822 11507 11507 E AndroidRuntime: Process: dnsfilter.android, PID: 11507
01-31 23:10:45.822 11507 11507 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{dnsfilter.android/dnsfilter.android.DNSProxyActivity}: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null object reference in method 'void dnsfilter.android.FilterConfig.setEntries(dnsfilter.ConfigUtil$HostFilterList[])'
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at dnsfilter.android.DNSProxyActivity.onCreate(DNSProxyActivity.java:603)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8944)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8913)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
01-31 23:10:45.822 11507 11507 E AndroidRuntime: 	... 12 more
01-31 23:10:45.822 11507 11507 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String dnsfilter.ConfigUtil$HostFilterList.category' on a null ob

**Comment by scollovati** [comment] 2024-02-07 12:13
> @IngoZenz Pleased to report the update arrived on F-Droid, and installs and works great. Thanks for fixing the issue.

Same here. Thanks for fixing the issue.

**Comment by IngoZenz** [comment] 2024-02-08 11:37
F-droid is updated with version 1.50.55.2 - so closing this issue

**Closed by IngoZenz** 2024-02-08 11:37 UTC
