### ISSUE TITLE
[BUG] Autostart isn't really autostarting

### ISSUE THREAD

**Issue by 0xlne** [IngoZenz/personaldnsfilter#75] opened 2020-03-25 22:04 UTC
Device: Android 10/Samsung Galaxy Note 10+

Selecting the "autostart" option indeed allows for DNSfilter to start automatically after a reboot of the device, but filtering itself doesn't seem to be activating until after manually accessing the app.

**Comment by IngoZenz** [comment] 2020-03-26 07:30
I cannot reproduce this issue.
Any other VPN client which might Autostart on your device and thus overrule pDNSf?

**Comment by 0xlne** [comment] 2020-04-04 19:28
No, this is the only app I use which triggers VPN.
I have tested this on a number of roms, including stock, & AOSP GSI (phh).

**Comment by IngoZenz** [comment] 2020-04-04 20:50
Very strange - can't reproduce this and seems it is working for others.
Please check trafficlog after boot. Are there requests logged?
Could you share your dnsfilter.conf file?
Is it working when setting "always on" VPN?

**Comment by 0xlne** [comment] 2020-04-12 07:52
I tested again in the latest release.
1: it gets stuck on "already attached service". I still need to press "Restart" to get it to really start.
I tried with both VPN always on, & the default option being disabled.
2 screenshot attached.
![Screenshot_20200412-094201](https://user-images.githubusercontent.com/26036905/79063669-3fcaf300-7ca3-11ea-9e71-42751a2c6cd1.png)

**Comment by IngoZenz** [comment] 2020-04-12 11:09
Ok...Thanks again for the update. I will need to check this. I might ask you for some additional tests in the next days.
I have some more questions:
Is network running at all in this situation? Or is it stuck. Is there something written to the traffic log in the personaldnsfilter log folder when it is not working?

**Comment by IngoZenz** [comment] 2020-04-12 18:54
The entries in trafficlog, are those from the time when it was not blocking?

**Comment by IngoZenz** [comment] 2020-04-13 14:41
One more thing: After you started the UI and you got this "Service already Running" message. What happens in case you continue browsing the web? Is it working? It should just log normally in your UI. Does it log?

**Comment by IngoZenz** [comment] 2020-05-23 13:44
No more Update => closing

**Closed by IngoZenz** 2020-05-23 13:44 UTC
